### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by praetoria** [emlai/emregex#1]
2.9.2017 20:55

Koodisi on selkeää ja fiksusti toteutettua. Muistinhallinta ja taulukon laajennus on hyvin toteutettu parseSeq funktiossa.

parseSeq-funktiossa on tosin bugi, joka johtaa segfaulttiin. Mikäli syötteessä on yksi ylimääräinen avaava sulku ja parseSeq funktiota kutsutaan seuraavasti: ```parseSeq(&node,')')```, parseSeq lukee nollatavun yli ja osuu laittomaan muistialueeseen.
Asian voi korjata vertaamalla parseSeqin while-loopissa tokenia sekä annettuun ```terminator```-muuttujaan että nollatavuun.

Samanlainen bugi on myös parseRange-funktiossa, kohdassa, jossa tarkistetaan useaa vaihtoehtoista merkkiä hakasulkeiden sisällä. Tällöin, jos sulkevaa hakasulkua ei ole, päädytään taas sallitun muistin ulkopuolelle. Tämän voi korjata samalla tavalla vertaamalla reRBracketin lisäksi myös nollatavuun.

Lisäksi kannattaisi muuttaa ```else``` parseRange-funktiossa ```else if (ch != 0)```:ksi, jotta vältyttäisiin nollan yli lukemiselta elsen sisällä.

```
static reNode parseRange(void) {
    reNode node;
    node.lowerbound = lex();
    int ch = lex();
    if (ch == '-') {
        // Contiguous range expressed with a hyphen, e.g. [a-z].
        node.type = reRange;
        node.upperbound = lex();
        if (lex() != reRBracket) error("expected ']' to terminate range");
    } else {
...
```

Muuten koodisi on melko idiomaattista ja selkeää C:tä, ja globaalin muuttujan ```root``` käyttö toimii hyvin kirjastossa.

**Comment by emillaine** [comment]
Kiitti, joo en oo kiinnittäny vielä yhtään huomiota käyttäjän syötteen validointiin joten tollasia bugeja varmaan on enemmänkin. Pitää korjata.
