### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by je-l** [emlai/emregex#2]
Moi

ladattu 19.2. 14:30

Ohjelma kääntyi hyvin, eikä virheitä tullut. Testejä en kuitenkaan saanut
toimimaan (ruby 2.3.1), "make test" tuotti virheilmoituksen 
```
Makefile:61: recipe
for target 'test' failed make: *** [test] Error 8
```

Muutamilla eri lausekkeilla kokeillen ohjelma vaikuttaa toimivan odotetusti.

Itse koodia oli tosi helppo lukea. Kommentointi oli kattavaa ja ohjelman rakenne
vaikutti järkevältä. Myös Testejä näyttää olevan laajasti, rajatapauksille ja
erilaisille syötteille.

Readmehen voisi varmaan lisätä vielä lyhyesti ohjelman käytöstä. Käyttö ei ole
monimutkaista, mutta on mukavampi suorittaa ohjelma kun tietää vähän mitä
odottaa.

Jos aikaa riittää, niin vaikkapa grep-tyylinen väritys matchaaviin osioihin
voisi olla kiva. En osaa kyllä sanoa kuinka helppo/vaikea tälläinen ominaisuus
on tehdä.

**Comment by emillaine** [comment]
Kiitti! Muokkasin readmetä palautteesi perusteella. Lisäsin myös ohjeet miten testit voi ajaa niin että saa paremmat virheilmoitukset. Komentolinjaväritys olisi varmaan semi helppo toteuttaa mutta en nyt jaksanut 😅.
